# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/st/stm32cubeclt_1.18.0/CMake/bin/cmake

# The command to remove a file.
RM = /opt/st/stm32cubeclt_1.18.0/CMake/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/michi/Documents/Semester-Thesis/magnecko-foot-header

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/michi/Documents/Semester-Thesis/magnecko-foot-header

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/st/stm32cubeclt_1.18.0/CMake/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/st/stm32cubeclt_1.18.0/CMake/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/michi/Documents/Semester-Thesis/magnecko-foot-header/CMakeFiles /home/michi/Documents/Semester-Thesis/magnecko-foot-header//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/michi/Documents/Semester-Thesis/magnecko-foot-header/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named MagneckoFoot_Header

# Build rule for target.
MagneckoFoot_Header: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MagneckoFoot_Header
.PHONY : MagneckoFoot_Header

# fast build rule for target.
MagneckoFoot_Header/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagneckoFoot_Header.dir/build.make CMakeFiles/MagneckoFoot_Header.dir/build
.PHONY : MagneckoFoot_Header/fast

#=============================================================================
# Target rules for targets named STM32_Drivers

# Build rule for target.
STM32_Drivers: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 STM32_Drivers
.PHONY : STM32_Drivers

# fast build rule for target.
STM32_Drivers/fast:
	$(MAKE) $(MAKESILENT) -f cmake/stm32cubemx/CMakeFiles/STM32_Drivers.dir/build.make cmake/stm32cubemx/CMakeFiles/STM32_Drivers.dir/build
.PHONY : STM32_Drivers/fast

#=============================================================================
# Target rules for targets named soes

# Build rule for target.
soes: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 soes
.PHONY : soes

# fast build rule for target.
soes/fast:
	$(MAKE) $(MAKESILENT) -f Libs/SOES_Wrapper/CMakeFiles/soes.dir/build.make Libs/SOES_Wrapper/CMakeFiles/soes.dir/build
.PHONY : soes/fast

Core/Src/adc.obj: Core/Src/adc.c.obj
.PHONY : Core/Src/adc.obj

# target to build an object file
Core/Src/adc.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagneckoFoot_Header.dir/build.make CMakeFiles/MagneckoFoot_Header.dir/Core/Src/adc.c.obj
.PHONY : Core/Src/adc.c.obj

Core/Src/adc.i: Core/Src/adc.c.i
.PHONY : Core/Src/adc.i

# target to preprocess a source file
Core/Src/adc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagneckoFoot_Header.dir/build.make CMakeFiles/MagneckoFoot_Header.dir/Core/Src/adc.c.i
.PHONY : Core/Src/adc.c.i

Core/Src/adc.s: Core/Src/adc.c.s
.PHONY : Core/Src/adc.s

# target to generate assembly for a file
Core/Src/adc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagneckoFoot_Header.dir/build.make CMakeFiles/MagneckoFoot_Header.dir/Core/Src/adc.c.s
.PHONY : Core/Src/adc.c.s

Core/Src/gpio.obj: Core/Src/gpio.c.obj
.PHONY : Core/Src/gpio.obj

# target to build an object file
Core/Src/gpio.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagneckoFoot_Header.dir/build.make CMakeFiles/MagneckoFoot_Header.dir/Core/Src/gpio.c.obj
.PHONY : Core/Src/gpio.c.obj

Core/Src/gpio.i: Core/Src/gpio.c.i
.PHONY : Core/Src/gpio.i

# target to preprocess a source file
Core/Src/gpio.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagneckoFoot_Header.dir/build.make CMakeFiles/MagneckoFoot_Header.dir/Core/Src/gpio.c.i
.PHONY : Core/Src/gpio.c.i

Core/Src/gpio.s: Core/Src/gpio.c.s
.PHONY : Core/Src/gpio.s

# target to generate assembly for a file
Core/Src/gpio.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagneckoFoot_Header.dir/build.make CMakeFiles/MagneckoFoot_Header.dir/Core/Src/gpio.c.s
.PHONY : Core/Src/gpio.c.s

Core/Src/i2c.obj: Core/Src/i2c.c.obj
.PHONY : Core/Src/i2c.obj

# target to build an object file
Core/Src/i2c.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagneckoFoot_Header.dir/build.make CMakeFiles/MagneckoFoot_Header.dir/Core/Src/i2c.c.obj
.PHONY : Core/Src/i2c.c.obj

Core/Src/i2c.i: Core/Src/i2c.c.i
.PHONY : Core/Src/i2c.i

# target to preprocess a source file
Core/Src/i2c.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagneckoFoot_Header.dir/build.make CMakeFiles/MagneckoFoot_Header.dir/Core/Src/i2c.c.i
.PHONY : Core/Src/i2c.c.i

Core/Src/i2c.s: Core/Src/i2c.c.s
.PHONY : Core/Src/i2c.s

# target to generate assembly for a file
Core/Src/i2c.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagneckoFoot_Header.dir/build.make CMakeFiles/MagneckoFoot_Header.dir/Core/Src/i2c.c.s
.PHONY : Core/Src/i2c.c.s

Core/Src/main.obj: Core/Src/main.cpp.obj
.PHONY : Core/Src/main.obj

# target to build an object file
Core/Src/main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagneckoFoot_Header.dir/build.make CMakeFiles/MagneckoFoot_Header.dir/Core/Src/main.cpp.obj
.PHONY : Core/Src/main.cpp.obj

Core/Src/main.i: Core/Src/main.cpp.i
.PHONY : Core/Src/main.i

# target to preprocess a source file
Core/Src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagneckoFoot_Header.dir/build.make CMakeFiles/MagneckoFoot_Header.dir/Core/Src/main.cpp.i
.PHONY : Core/Src/main.cpp.i

Core/Src/main.s: Core/Src/main.cpp.s
.PHONY : Core/Src/main.s

# target to generate assembly for a file
Core/Src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagneckoFoot_Header.dir/build.make CMakeFiles/MagneckoFoot_Header.dir/Core/Src/main.cpp.s
.PHONY : Core/Src/main.cpp.s

Core/Src/memorymap.obj: Core/Src/memorymap.c.obj
.PHONY : Core/Src/memorymap.obj

# target to build an object file
Core/Src/memorymap.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagneckoFoot_Header.dir/build.make CMakeFiles/MagneckoFoot_Header.dir/Core/Src/memorymap.c.obj
.PHONY : Core/Src/memorymap.c.obj

Core/Src/memorymap.i: Core/Src/memorymap.c.i
.PHONY : Core/Src/memorymap.i

# target to preprocess a source file
Core/Src/memorymap.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagneckoFoot_Header.dir/build.make CMakeFiles/MagneckoFoot_Header.dir/Core/Src/memorymap.c.i
.PHONY : Core/Src/memorymap.c.i

Core/Src/memorymap.s: Core/Src/memorymap.c.s
.PHONY : Core/Src/memorymap.s

# target to generate assembly for a file
Core/Src/memorymap.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagneckoFoot_Header.dir/build.make CMakeFiles/MagneckoFoot_Header.dir/Core/Src/memorymap.c.s
.PHONY : Core/Src/memorymap.c.s

Core/Src/spi.obj: Core/Src/spi.c.obj
.PHONY : Core/Src/spi.obj

# target to build an object file
Core/Src/spi.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagneckoFoot_Header.dir/build.make CMakeFiles/MagneckoFoot_Header.dir/Core/Src/spi.c.obj
.PHONY : Core/Src/spi.c.obj

Core/Src/spi.i: Core/Src/spi.c.i
.PHONY : Core/Src/spi.i

# target to preprocess a source file
Core/Src/spi.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagneckoFoot_Header.dir/build.make CMakeFiles/MagneckoFoot_Header.dir/Core/Src/spi.c.i
.PHONY : Core/Src/spi.c.i

Core/Src/spi.s: Core/Src/spi.c.s
.PHONY : Core/Src/spi.s

# target to generate assembly for a file
Core/Src/spi.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagneckoFoot_Header.dir/build.make CMakeFiles/MagneckoFoot_Header.dir/Core/Src/spi.c.s
.PHONY : Core/Src/spi.c.s

Core/Src/stm32h7xx_hal_msp.obj: Core/Src/stm32h7xx_hal_msp.c.obj
.PHONY : Core/Src/stm32h7xx_hal_msp.obj

# target to build an object file
Core/Src/stm32h7xx_hal_msp.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagneckoFoot_Header.dir/build.make CMakeFiles/MagneckoFoot_Header.dir/Core/Src/stm32h7xx_hal_msp.c.obj
.PHONY : Core/Src/stm32h7xx_hal_msp.c.obj

Core/Src/stm32h7xx_hal_msp.i: Core/Src/stm32h7xx_hal_msp.c.i
.PHONY : Core/Src/stm32h7xx_hal_msp.i

# target to preprocess a source file
Core/Src/stm32h7xx_hal_msp.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagneckoFoot_Header.dir/build.make CMakeFiles/MagneckoFoot_Header.dir/Core/Src/stm32h7xx_hal_msp.c.i
.PHONY : Core/Src/stm32h7xx_hal_msp.c.i

Core/Src/stm32h7xx_hal_msp.s: Core/Src/stm32h7xx_hal_msp.c.s
.PHONY : Core/Src/stm32h7xx_hal_msp.s

# target to generate assembly for a file
Core/Src/stm32h7xx_hal_msp.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagneckoFoot_Header.dir/build.make CMakeFiles/MagneckoFoot_Header.dir/Core/Src/stm32h7xx_hal_msp.c.s
.PHONY : Core/Src/stm32h7xx_hal_msp.c.s

Core/Src/stm32h7xx_it.obj: Core/Src/stm32h7xx_it.c.obj
.PHONY : Core/Src/stm32h7xx_it.obj

# target to build an object file
Core/Src/stm32h7xx_it.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagneckoFoot_Header.dir/build.make CMakeFiles/MagneckoFoot_Header.dir/Core/Src/stm32h7xx_it.c.obj
.PHONY : Core/Src/stm32h7xx_it.c.obj

Core/Src/stm32h7xx_it.i: Core/Src/stm32h7xx_it.c.i
.PHONY : Core/Src/stm32h7xx_it.i

# target to preprocess a source file
Core/Src/stm32h7xx_it.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagneckoFoot_Header.dir/build.make CMakeFiles/MagneckoFoot_Header.dir/Core/Src/stm32h7xx_it.c.i
.PHONY : Core/Src/stm32h7xx_it.c.i

Core/Src/stm32h7xx_it.s: Core/Src/stm32h7xx_it.c.s
.PHONY : Core/Src/stm32h7xx_it.s

# target to generate assembly for a file
Core/Src/stm32h7xx_it.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagneckoFoot_Header.dir/build.make CMakeFiles/MagneckoFoot_Header.dir/Core/Src/stm32h7xx_it.c.s
.PHONY : Core/Src/stm32h7xx_it.c.s

Core/Src/syscalls.obj: Core/Src/syscalls.c.obj
.PHONY : Core/Src/syscalls.obj

# target to build an object file
Core/Src/syscalls.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagneckoFoot_Header.dir/build.make CMakeFiles/MagneckoFoot_Header.dir/Core/Src/syscalls.c.obj
.PHONY : Core/Src/syscalls.c.obj

Core/Src/syscalls.i: Core/Src/syscalls.c.i
.PHONY : Core/Src/syscalls.i

# target to preprocess a source file
Core/Src/syscalls.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagneckoFoot_Header.dir/build.make CMakeFiles/MagneckoFoot_Header.dir/Core/Src/syscalls.c.i
.PHONY : Core/Src/syscalls.c.i

Core/Src/syscalls.s: Core/Src/syscalls.c.s
.PHONY : Core/Src/syscalls.s

# target to generate assembly for a file
Core/Src/syscalls.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagneckoFoot_Header.dir/build.make CMakeFiles/MagneckoFoot_Header.dir/Core/Src/syscalls.c.s
.PHONY : Core/Src/syscalls.c.s

Core/Src/sysmem.obj: Core/Src/sysmem.c.obj
.PHONY : Core/Src/sysmem.obj

# target to build an object file
Core/Src/sysmem.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagneckoFoot_Header.dir/build.make CMakeFiles/MagneckoFoot_Header.dir/Core/Src/sysmem.c.obj
.PHONY : Core/Src/sysmem.c.obj

Core/Src/sysmem.i: Core/Src/sysmem.c.i
.PHONY : Core/Src/sysmem.i

# target to preprocess a source file
Core/Src/sysmem.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagneckoFoot_Header.dir/build.make CMakeFiles/MagneckoFoot_Header.dir/Core/Src/sysmem.c.i
.PHONY : Core/Src/sysmem.c.i

Core/Src/sysmem.s: Core/Src/sysmem.c.s
.PHONY : Core/Src/sysmem.s

# target to generate assembly for a file
Core/Src/sysmem.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagneckoFoot_Header.dir/build.make CMakeFiles/MagneckoFoot_Header.dir/Core/Src/sysmem.c.s
.PHONY : Core/Src/sysmem.c.s

Core/Src/tim.obj: Core/Src/tim.c.obj
.PHONY : Core/Src/tim.obj

# target to build an object file
Core/Src/tim.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagneckoFoot_Header.dir/build.make CMakeFiles/MagneckoFoot_Header.dir/Core/Src/tim.c.obj
.PHONY : Core/Src/tim.c.obj

Core/Src/tim.i: Core/Src/tim.c.i
.PHONY : Core/Src/tim.i

# target to preprocess a source file
Core/Src/tim.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagneckoFoot_Header.dir/build.make CMakeFiles/MagneckoFoot_Header.dir/Core/Src/tim.c.i
.PHONY : Core/Src/tim.c.i

Core/Src/tim.s: Core/Src/tim.c.s
.PHONY : Core/Src/tim.s

# target to generate assembly for a file
Core/Src/tim.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagneckoFoot_Header.dir/build.make CMakeFiles/MagneckoFoot_Header.dir/Core/Src/tim.c.s
.PHONY : Core/Src/tim.c.s

Drivers/VL53LMZ_ULD_API/Platform/platform.obj: Drivers/VL53LMZ_ULD_API/Platform/platform.c.obj
.PHONY : Drivers/VL53LMZ_ULD_API/Platform/platform.obj

# target to build an object file
Drivers/VL53LMZ_ULD_API/Platform/platform.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagneckoFoot_Header.dir/build.make CMakeFiles/MagneckoFoot_Header.dir/Drivers/VL53LMZ_ULD_API/Platform/platform.c.obj
.PHONY : Drivers/VL53LMZ_ULD_API/Platform/platform.c.obj

Drivers/VL53LMZ_ULD_API/Platform/platform.i: Drivers/VL53LMZ_ULD_API/Platform/platform.c.i
.PHONY : Drivers/VL53LMZ_ULD_API/Platform/platform.i

# target to preprocess a source file
Drivers/VL53LMZ_ULD_API/Platform/platform.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagneckoFoot_Header.dir/build.make CMakeFiles/MagneckoFoot_Header.dir/Drivers/VL53LMZ_ULD_API/Platform/platform.c.i
.PHONY : Drivers/VL53LMZ_ULD_API/Platform/platform.c.i

Drivers/VL53LMZ_ULD_API/Platform/platform.s: Drivers/VL53LMZ_ULD_API/Platform/platform.c.s
.PHONY : Drivers/VL53LMZ_ULD_API/Platform/platform.s

# target to generate assembly for a file
Drivers/VL53LMZ_ULD_API/Platform/platform.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagneckoFoot_Header.dir/build.make CMakeFiles/MagneckoFoot_Header.dir/Drivers/VL53LMZ_ULD_API/Platform/platform.c.s
.PHONY : Drivers/VL53LMZ_ULD_API/Platform/platform.c.s

Drivers/VL53LMZ_ULD_API/src/vl53lmz_api.obj: Drivers/VL53LMZ_ULD_API/src/vl53lmz_api.c.obj
.PHONY : Drivers/VL53LMZ_ULD_API/src/vl53lmz_api.obj

# target to build an object file
Drivers/VL53LMZ_ULD_API/src/vl53lmz_api.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagneckoFoot_Header.dir/build.make CMakeFiles/MagneckoFoot_Header.dir/Drivers/VL53LMZ_ULD_API/src/vl53lmz_api.c.obj
.PHONY : Drivers/VL53LMZ_ULD_API/src/vl53lmz_api.c.obj

Drivers/VL53LMZ_ULD_API/src/vl53lmz_api.i: Drivers/VL53LMZ_ULD_API/src/vl53lmz_api.c.i
.PHONY : Drivers/VL53LMZ_ULD_API/src/vl53lmz_api.i

# target to preprocess a source file
Drivers/VL53LMZ_ULD_API/src/vl53lmz_api.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagneckoFoot_Header.dir/build.make CMakeFiles/MagneckoFoot_Header.dir/Drivers/VL53LMZ_ULD_API/src/vl53lmz_api.c.i
.PHONY : Drivers/VL53LMZ_ULD_API/src/vl53lmz_api.c.i

Drivers/VL53LMZ_ULD_API/src/vl53lmz_api.s: Drivers/VL53LMZ_ULD_API/src/vl53lmz_api.c.s
.PHONY : Drivers/VL53LMZ_ULD_API/src/vl53lmz_api.s

# target to generate assembly for a file
Drivers/VL53LMZ_ULD_API/src/vl53lmz_api.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagneckoFoot_Header.dir/build.make CMakeFiles/MagneckoFoot_Header.dir/Drivers/VL53LMZ_ULD_API/src/vl53lmz_api.c.s
.PHONY : Drivers/VL53LMZ_ULD_API/src/vl53lmz_api.c.s

Drivers/VL53LMZ_ULD_API/src/vl53lmz_plugin_infos.obj: Drivers/VL53LMZ_ULD_API/src/vl53lmz_plugin_infos.c.obj
.PHONY : Drivers/VL53LMZ_ULD_API/src/vl53lmz_plugin_infos.obj

# target to build an object file
Drivers/VL53LMZ_ULD_API/src/vl53lmz_plugin_infos.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagneckoFoot_Header.dir/build.make CMakeFiles/MagneckoFoot_Header.dir/Drivers/VL53LMZ_ULD_API/src/vl53lmz_plugin_infos.c.obj
.PHONY : Drivers/VL53LMZ_ULD_API/src/vl53lmz_plugin_infos.c.obj

Drivers/VL53LMZ_ULD_API/src/vl53lmz_plugin_infos.i: Drivers/VL53LMZ_ULD_API/src/vl53lmz_plugin_infos.c.i
.PHONY : Drivers/VL53LMZ_ULD_API/src/vl53lmz_plugin_infos.i

# target to preprocess a source file
Drivers/VL53LMZ_ULD_API/src/vl53lmz_plugin_infos.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagneckoFoot_Header.dir/build.make CMakeFiles/MagneckoFoot_Header.dir/Drivers/VL53LMZ_ULD_API/src/vl53lmz_plugin_infos.c.i
.PHONY : Drivers/VL53LMZ_ULD_API/src/vl53lmz_plugin_infos.c.i

Drivers/VL53LMZ_ULD_API/src/vl53lmz_plugin_infos.s: Drivers/VL53LMZ_ULD_API/src/vl53lmz_plugin_infos.c.s
.PHONY : Drivers/VL53LMZ_ULD_API/src/vl53lmz_plugin_infos.s

# target to generate assembly for a file
Drivers/VL53LMZ_ULD_API/src/vl53lmz_plugin_infos.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagneckoFoot_Header.dir/build.make CMakeFiles/MagneckoFoot_Header.dir/Drivers/VL53LMZ_ULD_API/src/vl53lmz_plugin_infos.c.s
.PHONY : Drivers/VL53LMZ_ULD_API/src/vl53lmz_plugin_infos.c.s

Libs/Controller/FootController.obj: Libs/Controller/FootController.cpp.obj
.PHONY : Libs/Controller/FootController.obj

# target to build an object file
Libs/Controller/FootController.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagneckoFoot_Header.dir/build.make CMakeFiles/MagneckoFoot_Header.dir/Libs/Controller/FootController.cpp.obj
.PHONY : Libs/Controller/FootController.cpp.obj

Libs/Controller/FootController.i: Libs/Controller/FootController.cpp.i
.PHONY : Libs/Controller/FootController.i

# target to preprocess a source file
Libs/Controller/FootController.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagneckoFoot_Header.dir/build.make CMakeFiles/MagneckoFoot_Header.dir/Libs/Controller/FootController.cpp.i
.PHONY : Libs/Controller/FootController.cpp.i

Libs/Controller/FootController.s: Libs/Controller/FootController.cpp.s
.PHONY : Libs/Controller/FootController.s

# target to generate assembly for a file
Libs/Controller/FootController.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagneckoFoot_Header.dir/build.make CMakeFiles/MagneckoFoot_Header.dir/Libs/Controller/FootController.cpp.s
.PHONY : Libs/Controller/FootController.cpp.s

Libs/FSM/FSM.obj: Libs/FSM/FSM.cpp.obj
.PHONY : Libs/FSM/FSM.obj

# target to build an object file
Libs/FSM/FSM.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagneckoFoot_Header.dir/build.make CMakeFiles/MagneckoFoot_Header.dir/Libs/FSM/FSM.cpp.obj
.PHONY : Libs/FSM/FSM.cpp.obj

Libs/FSM/FSM.i: Libs/FSM/FSM.cpp.i
.PHONY : Libs/FSM/FSM.i

# target to preprocess a source file
Libs/FSM/FSM.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagneckoFoot_Header.dir/build.make CMakeFiles/MagneckoFoot_Header.dir/Libs/FSM/FSM.cpp.i
.PHONY : Libs/FSM/FSM.cpp.i

Libs/FSM/FSM.s: Libs/FSM/FSM.cpp.s
.PHONY : Libs/FSM/FSM.s

# target to generate assembly for a file
Libs/FSM/FSM.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagneckoFoot_Header.dir/build.make CMakeFiles/MagneckoFoot_Header.dir/Libs/FSM/FSM.cpp.s
.PHONY : Libs/FSM/FSM.cpp.s

Libs/Sensors/BNO086.obj: Libs/Sensors/BNO086.cpp.obj
.PHONY : Libs/Sensors/BNO086.obj

# target to build an object file
Libs/Sensors/BNO086.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagneckoFoot_Header.dir/build.make CMakeFiles/MagneckoFoot_Header.dir/Libs/Sensors/BNO086.cpp.obj
.PHONY : Libs/Sensors/BNO086.cpp.obj

Libs/Sensors/BNO086.i: Libs/Sensors/BNO086.cpp.i
.PHONY : Libs/Sensors/BNO086.i

# target to preprocess a source file
Libs/Sensors/BNO086.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagneckoFoot_Header.dir/build.make CMakeFiles/MagneckoFoot_Header.dir/Libs/Sensors/BNO086.cpp.i
.PHONY : Libs/Sensors/BNO086.cpp.i

Libs/Sensors/BNO086.s: Libs/Sensors/BNO086.cpp.s
.PHONY : Libs/Sensors/BNO086.s

# target to generate assembly for a file
Libs/Sensors/BNO086.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagneckoFoot_Header.dir/build.make CMakeFiles/MagneckoFoot_Header.dir/Libs/Sensors/BNO086.cpp.s
.PHONY : Libs/Sensors/BNO086.cpp.s

Libs/Sensors/LDC1614.obj: Libs/Sensors/LDC1614.cpp.obj
.PHONY : Libs/Sensors/LDC1614.obj

# target to build an object file
Libs/Sensors/LDC1614.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagneckoFoot_Header.dir/build.make CMakeFiles/MagneckoFoot_Header.dir/Libs/Sensors/LDC1614.cpp.obj
.PHONY : Libs/Sensors/LDC1614.cpp.obj

Libs/Sensors/LDC1614.i: Libs/Sensors/LDC1614.cpp.i
.PHONY : Libs/Sensors/LDC1614.i

# target to preprocess a source file
Libs/Sensors/LDC1614.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagneckoFoot_Header.dir/build.make CMakeFiles/MagneckoFoot_Header.dir/Libs/Sensors/LDC1614.cpp.i
.PHONY : Libs/Sensors/LDC1614.cpp.i

Libs/Sensors/LDC1614.s: Libs/Sensors/LDC1614.cpp.s
.PHONY : Libs/Sensors/LDC1614.s

# target to generate assembly for a file
Libs/Sensors/LDC1614.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagneckoFoot_Header.dir/build.make CMakeFiles/MagneckoFoot_Header.dir/Libs/Sensors/LDC1614.cpp.s
.PHONY : Libs/Sensors/LDC1614.cpp.s

Libs/Sensors/TMAG5273.obj: Libs/Sensors/TMAG5273.cpp.obj
.PHONY : Libs/Sensors/TMAG5273.obj

# target to build an object file
Libs/Sensors/TMAG5273.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagneckoFoot_Header.dir/build.make CMakeFiles/MagneckoFoot_Header.dir/Libs/Sensors/TMAG5273.cpp.obj
.PHONY : Libs/Sensors/TMAG5273.cpp.obj

Libs/Sensors/TMAG5273.i: Libs/Sensors/TMAG5273.cpp.i
.PHONY : Libs/Sensors/TMAG5273.i

# target to preprocess a source file
Libs/Sensors/TMAG5273.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagneckoFoot_Header.dir/build.make CMakeFiles/MagneckoFoot_Header.dir/Libs/Sensors/TMAG5273.cpp.i
.PHONY : Libs/Sensors/TMAG5273.cpp.i

Libs/Sensors/TMAG5273.s: Libs/Sensors/TMAG5273.cpp.s
.PHONY : Libs/Sensors/TMAG5273.s

# target to generate assembly for a file
Libs/Sensors/TMAG5273.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagneckoFoot_Header.dir/build.make CMakeFiles/MagneckoFoot_Header.dir/Libs/Sensors/TMAG5273.cpp.s
.PHONY : Libs/Sensors/TMAG5273.cpp.s

Libs/Sensors/VL53L7CH.obj: Libs/Sensors/VL53L7CH.cpp.obj
.PHONY : Libs/Sensors/VL53L7CH.obj

# target to build an object file
Libs/Sensors/VL53L7CH.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagneckoFoot_Header.dir/build.make CMakeFiles/MagneckoFoot_Header.dir/Libs/Sensors/VL53L7CH.cpp.obj
.PHONY : Libs/Sensors/VL53L7CH.cpp.obj

Libs/Sensors/VL53L7CH.i: Libs/Sensors/VL53L7CH.cpp.i
.PHONY : Libs/Sensors/VL53L7CH.i

# target to preprocess a source file
Libs/Sensors/VL53L7CH.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagneckoFoot_Header.dir/build.make CMakeFiles/MagneckoFoot_Header.dir/Libs/Sensors/VL53L7CH.cpp.i
.PHONY : Libs/Sensors/VL53L7CH.cpp.i

Libs/Sensors/VL53L7CH.s: Libs/Sensors/VL53L7CH.cpp.s
.PHONY : Libs/Sensors/VL53L7CH.s

# target to generate assembly for a file
Libs/Sensors/VL53L7CH.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagneckoFoot_Header.dir/build.make CMakeFiles/MagneckoFoot_Header.dir/Libs/Sensors/VL53L7CH.cpp.s
.PHONY : Libs/Sensors/VL53L7CH.cpp.s

startup_stm32h725xx.obj: startup_stm32h725xx.s.obj
.PHONY : startup_stm32h725xx.obj

# target to build an object file
startup_stm32h725xx.s.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagneckoFoot_Header.dir/build.make CMakeFiles/MagneckoFoot_Header.dir/startup_stm32h725xx.s.obj
.PHONY : startup_stm32h725xx.s.obj

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... MagneckoFoot_Header"
	@echo "... STM32_Drivers"
	@echo "... soes"
	@echo "... Core/Src/adc.obj"
	@echo "... Core/Src/adc.i"
	@echo "... Core/Src/adc.s"
	@echo "... Core/Src/gpio.obj"
	@echo "... Core/Src/gpio.i"
	@echo "... Core/Src/gpio.s"
	@echo "... Core/Src/i2c.obj"
	@echo "... Core/Src/i2c.i"
	@echo "... Core/Src/i2c.s"
	@echo "... Core/Src/main.obj"
	@echo "... Core/Src/main.i"
	@echo "... Core/Src/main.s"
	@echo "... Core/Src/memorymap.obj"
	@echo "... Core/Src/memorymap.i"
	@echo "... Core/Src/memorymap.s"
	@echo "... Core/Src/spi.obj"
	@echo "... Core/Src/spi.i"
	@echo "... Core/Src/spi.s"
	@echo "... Core/Src/stm32h7xx_hal_msp.obj"
	@echo "... Core/Src/stm32h7xx_hal_msp.i"
	@echo "... Core/Src/stm32h7xx_hal_msp.s"
	@echo "... Core/Src/stm32h7xx_it.obj"
	@echo "... Core/Src/stm32h7xx_it.i"
	@echo "... Core/Src/stm32h7xx_it.s"
	@echo "... Core/Src/syscalls.obj"
	@echo "... Core/Src/syscalls.i"
	@echo "... Core/Src/syscalls.s"
	@echo "... Core/Src/sysmem.obj"
	@echo "... Core/Src/sysmem.i"
	@echo "... Core/Src/sysmem.s"
	@echo "... Core/Src/tim.obj"
	@echo "... Core/Src/tim.i"
	@echo "... Core/Src/tim.s"
	@echo "... Drivers/VL53LMZ_ULD_API/Platform/platform.obj"
	@echo "... Drivers/VL53LMZ_ULD_API/Platform/platform.i"
	@echo "... Drivers/VL53LMZ_ULD_API/Platform/platform.s"
	@echo "... Drivers/VL53LMZ_ULD_API/src/vl53lmz_api.obj"
	@echo "... Drivers/VL53LMZ_ULD_API/src/vl53lmz_api.i"
	@echo "... Drivers/VL53LMZ_ULD_API/src/vl53lmz_api.s"
	@echo "... Drivers/VL53LMZ_ULD_API/src/vl53lmz_plugin_infos.obj"
	@echo "... Drivers/VL53LMZ_ULD_API/src/vl53lmz_plugin_infos.i"
	@echo "... Drivers/VL53LMZ_ULD_API/src/vl53lmz_plugin_infos.s"
	@echo "... Libs/Controller/FootController.obj"
	@echo "... Libs/Controller/FootController.i"
	@echo "... Libs/Controller/FootController.s"
	@echo "... Libs/FSM/FSM.obj"
	@echo "... Libs/FSM/FSM.i"
	@echo "... Libs/FSM/FSM.s"
	@echo "... Libs/Sensors/BNO086.obj"
	@echo "... Libs/Sensors/BNO086.i"
	@echo "... Libs/Sensors/BNO086.s"
	@echo "... Libs/Sensors/LDC1614.obj"
	@echo "... Libs/Sensors/LDC1614.i"
	@echo "... Libs/Sensors/LDC1614.s"
	@echo "... Libs/Sensors/TMAG5273.obj"
	@echo "... Libs/Sensors/TMAG5273.i"
	@echo "... Libs/Sensors/TMAG5273.s"
	@echo "... Libs/Sensors/VL53L7CH.obj"
	@echo "... Libs/Sensors/VL53L7CH.i"
	@echo "... Libs/Sensors/VL53L7CH.s"
	@echo "... startup_stm32h725xx.obj"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

